LoLTool\Bundle\LoLToolBundle\Entity\Player:
    type: entity
    table: null
    repositoryClass: LoLTool\Bundle\LoLToolBundle\Entity\PlayerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        playerId:
            type: integer
        summonerIconId:
            type: integer
        summonerLevel:
            type: integer
    lifecycleCallbacks: {  }
    oneToOne:
        league_3v3:
          targetEntity: League
        league_5v5:
          targetEntity: League
        league:
          targetEntity: League