admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

lo_l_tool:
    resource: "@LoLToolBundle/Resources/config/routing.yml"
    prefix:   /

